name            = "loop-messenger"
main            = "dist/server/index.mjs"
compatibility_date = "2025-06-01"
account_id      = "d5a1cd03b76f467430034af64a7062fd"

[assets]
directory = "dist/client"
binding   = "ASSETS"

[vars]
VITE_API_BASE = "https://messenger.rald.cloud"

[[routes]]
pattern   = "chat.rald.cloud/*"
zone_name = "rald.cloud"

[observability]
enabled           = true
head_sampling_rate = 1
